# Generated by Django 5.1.5 on 2025-02-05 12:50

from django.db import migrations


def load_fixtures(apps, schema_editor):
    """
    Load fixtures into the database.
    """
    from django.core.management import call_command

    fixtures = [
        "content_types.json",
        'permissions.json',
        'users.json',
        'groups.json',
        'expense_categories.json',
        'transactions.json',
        'user_profiles.json',
        'budgets.json',
    ]

    for fixture in fixtures:
        call_command('loaddata', f'walletmate_app/fixtures/{fixture}')


class Migration(migrations.Migration):

    dependencies = [
        ('walletmate_app', '0002_alter_transaction_user'),
    ]

    operations = [
        migrations.RunPython(load_fixtures),
    ]
